//
// Generated by dtk
// Translation Unit: d_a_kytag03.cpp
//
#include "JSystem/JKernel/JKRHeap.h"
#include "f_op/f_op_actor_mng.h"
#include "f_op/f_op_actor_mng.h"
#include "d/d_com_inf_game.h"
#include "dolphin/types.h"

class kytag03_class {
public:
    /* 0x00 */ u8 pad;
    /* 0x01 */ request_of_phase_process_class mPhase;
};

/* 00000078-0000015C       .text useHeapInit__FP10fopAc_ac_c */
void useHeapInit(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 0000015C-000001D8       .text daKytag03_Draw__FP13kytag03_class */
void daKytag03_Draw(kytag03_class*) {
    /* Nonmatching */

}

/* 000001D8-00000280       .text draw_SUB__FP13kytag03_class */
void draw_SUB(kytag03_class*) {
    /* Nonmatching */
}

/* 00000280-0000050C       .text daKytag03_Execute__FP13kytag03_class */
void daKytag03_Execute(kytag03_class*) {
    /* Nonmatching */
}

/* 0000050C-00000514       .text daKytag03_IsDelete__FP13kytag03_class */
BOOL daKytag03_IsDelete(kytag03_class*) {
    return true;
}

/* 00000514-00000544       .text daKytag03_Delete__FP13kytag03_class */
void daKytag03_Delete(kytag03_class*) {
    /* Nonmatching */
}

/* 00000544-00000604       .text daKytag03_Create__FP10fopAc_ac_c */
void daKytag03_Create(fopAc_ac_c* i_this) {
    /* Nonmatching */
    PhaseState PVar1;

    fopAcM_SetupActor(i_this, kytag03_class);
    kytag03_class *a_this = (kytag03_class*)i_this;
    PVar1 = dComIfG_resLoad(&a_this->mPhase, "KYTAG03");
    if (PVar1 == cPhs_COMPLEATE_e) {
        if (fopAcM_entrySolidHeap(i_this,(heapCallbackFunc)useHeapInit,0x4c30)) {
            PVar1 = cPhs_ERROR_e;
        }
        else {
            *(undefined *)&param_1[1].parent.parent.mpProf = 0;
            param_1[1].parent.parent.mLyTg.parent.parent.mpPrevNode = (node_class *)0x0;
            *(char *)((int)&param_1[1].parent.parent.mpProf + 1) =
                (char)(param_1->parent).parent.mParameters;
            *(undefined *)((int)&param_1[1].parent.parent.mpProf + 2) = 0;
            *(undefined *)&param_1[1].parent.parent.mpCtRq = 0;
            *(undefined *)((int)&param_1[1].parent.parent.mpProf + 3) = 0;
        }
    }
    return PVar1;
}

