//
// Generated by dtk
// Translation Unit: d_a_obj_tower.cpp
//
#include "f_op/f_op_actor_mng.h"
#include "d/d_resorce.h"
#include "d/d_com_inf_game.h"
#include "d/d_bg_w.h"
#include "m_Do/m_Do_mtx.h"

class daObjTower_c : public fopAc_ac_c{
public:
    int CreateHeap();
    void CreateInit();
    void set_mtx();
public:
    int pad;
    int padd;
    dBgW* mpBgW;
    J3DModel *mpModel;
    Mtx* mMtx;
    int paddd;
};

/* 00000078-00000098       .text CheckCreateHeap__FP10fopAc_ac_c */
void CheckCreateHeap(fopAc_ac_c*) {
    /* Nonmatching */
}

/* 00000098-0000020C       .text CreateHeap__12daObjTower_cFv */
int daObjTower_c::CreateHeap() {
    J3DModelData *pModel;
    u64 uVar1;
    J3DModel *pJVar2;
    dBgW *this_00;
    cBgD_t *pData;
    bool uVar3;
    bool bVar4;

    pModel = (J3DModelData *) dComIfG_getObjectRes("X_tower", 4);
    JUT_ASSERT(0x56, pModel);

    pJVar2 = mDoExt_J3DModel__create(pModel,0,0x11020203);
    mpModel = pJVar2;
    if (this->mpModel == (J3DModel *)0x0) {
        bVar4 = false;
    } else {
        MTXTrans(mDoMtx_stack_c::now, current.pos.x, current.pos.y, current.pos.z);
        mDoMtx_YrotM(mDoMtx_stack_c::now, current.angle.y);
        mDoMtx_stack_c::scaleM(mScale.x, mScale.y, mScale.z);
        MTXCopy(mDoMtx_stack_c::now,mCullMtx);
        this_00 = new dBgW(); //(dBgW *)JKernel::operator_new(0xbc);
        if (this_00 != NULL) {
            this_00 = new dBgW();
        }
        this->mpBgW = this_00;
        if (this->mpBgW == NULL) {
            bVar4 = false;
        } else {
            pData = (cBgD_t *)dComIfG_getObjectRes("X_tower", 7);
            uVar3 = mpBgW->Set((cBgD_t*)dComIfG_getObjectRes("X_tower", 7), cBgW::MOVE_BG_e, mMtx);
            bVar4 = (uVar3 & 0xff) == 0;
        }
    }
    return bVar4;
}

/* 0000020C-0000028C       .text CreateInit__12daObjTower_cFv */
void daObjTower_c::CreateInit() {
    /* Nonmatching */
}

/* 0000028C-0000030C       .text set_mtx__12daObjTower_cFv */
void daObjTower_c::set_mtx() {
    /* Nonmatching */
}

/* 0000030C-000003DC       .text daObjTower_Create__FPv */
static void daObjTower_Create(void*) {
    /* Nonmatching */
}

/* 000003DC-00000444       .text daObjTower_Delete__FPv */
static void daObjTower_Delete(void*) {
    /* Nonmatching */
}

/* 00000444-000004E8       .text daObjTower_Draw__FPv */
static void daObjTower_Draw(void*) {
    /* Nonmatching */
}

/* 000004E8-00000568       .text daObjTower_Execute__FPv */
static void daObjTower_Execute(void*) {
    /* Nonmatching */
}

/* 00000568-00000570       .text daObjTower_IsDelete__FPv */
static BOOL daObjTower_IsDelete(void*) {
    return true;
}

